name: clumping-factor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - h5py
  - matplotlib
  - pytest
  - pip
  - pip:
      - illustris-python
      - Pylians
      - -e .
