name: clumping-factor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.11
  - h5py
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - ipykernel
  - psutil
  - pytest
  - pip
  - pip:
      - illustris-python
      - -e .
