#!/bin/bash

set -euo pipefail

SNAPSHOTS="${SNAPSHOTS:?Set SNAPSHOTS to a space-separated list, for example '40 50 60 70 80'.}"
BASE_PATH="${BASE_PATH:-../tng100-3/output}"
SIMULATION_NAME="${SIMULATION_NAME:-}"
PARTICLE="${PARTICLE:-gas}"
BACKEND="${BACKEND:-sphere}"
GRID="${GRID:-256}"
NCPUS="${NCPUS:-8}"
THREADS="${THREADS:-${NCPUS}}"
MAX_CONCURRENT="${MAX_CONCURRENT:-8}"
MEM="${MEM:-32gb}"
WALLTIME="${WALLTIME:-08:00:00}"
QUEUE="${QUEUE:-mini}"
CONDA_ENV="${CONDA_ENV:-clumping-factor}"
RADIUS_BINS="${RADIUS_BINS:-10}"
RADIUS_BIN_BATCH_SIZE="${RADIUS_BIN_BATCH_SIZE:-2}"
RADIUS_MODE="${RADIUS_MODE:-sphere}"
MAS="${MAS:-CIC}"
LOAD_MODE="${LOAD_MODE:-chunked}"
CHUNK_SIZE="${CHUNK_SIZE:-1000000}"
MAX_FULL_LOAD_GB="${MAX_FULL_LOAD_GB:-16}"
MEMORY_SAFETY_FRACTION="${MEMORY_SAFETY_FRACTION:-0.1}"
SUMMARY_CACHE="${SUMMARY_CACHE:-auto}"
SUMMARY_CACHE_DIR="${SUMMARY_CACHE_DIR:-results/.cache/summaries}"
WORK_PARTITION="${WORK_PARTITION:-auto}"
MAX_FILE_READERS="${MAX_FILE_READERS:-2}"
CLUMPING_MAX_GRID_CELLS="${CLUMPING_MAX_GRID_CELLS:-}"
PROGRESS_INTERVAL="${PROGRESS_INTERVAL:-25}"
VERBOSE="${VERBOSE:-1}"
TARGET_PARTICLE_TYPE="${TARGET_PARTICLE_TYPE:-}"
TARGET_BACKEND="${TARGET_BACKEND:-}"
MASK_PARTICLE_TYPE="${MASK_PARTICLE_TYPE:-}"
MASK_BACKEND="${MASK_BACKEND:-}"
TARGET_RADIUS_MODE="${TARGET_RADIUS_MODE:-}"
MASK_RADIUS_MODE="${MASK_RADIUS_MODE:-}"
SIGMA_BAR_ION_CM2="${SIGMA_BAR_ION_CM2:-}"
SIGMA_BAR_ION_SOURCE="${SIGMA_BAR_ION_SOURCE:-}"

if [[ -z "${SIMULATION_NAME}" ]]; then
  base_trimmed="${BASE_PATH%/}"
  SIMULATION_NAME="$(basename "${base_trimmed}")"
  if [[ "${SIMULATION_NAME}" == "output" ]]; then
    SIMULATION_NAME="$(basename "$(dirname "${base_trimmed}")")"
  fi
fi

read -r -a snapshot_array <<< "${SNAPSHOTS}"
if (( ${#snapshot_array[@]} == 0 )); then
  echo "SNAPSHOTS must contain at least one snapshot number." >&2
  exit 1
fi
snapshots_csv="$(IFS=:; echo "${snapshot_array[*]}")"
last_index=$((${#snapshot_array[@]} - 1))
project_dir="$(pwd)"
job_simulation_name="${SIMULATION_NAME//[^A-Za-z0-9_]/_}"
name="cfz_${job_simulation_name}_${PARTICLE}_${BACKEND}_g${GRID}"
mkdir -p "logs/${SIMULATION_NAME}" "results/${SIMULATION_NAME}"

qsub \
  -N "${name}" \
  -q "${QUEUE}" \
  -J "0-${last_index}%${MAX_CONCURRENT}" \
  -o "${project_dir}/logs/${SIMULATION_NAME}/${name}.out" \
  -e "${project_dir}/logs/${SIMULATION_NAME}/${name}.err" \
  -l "select=1:ncpus=${NCPUS}:mem=${MEM}" \
  -l "walltime=${WALLTIME}" \
  -v "PROJECT_DIR=${project_dir},SNAPSHOTS_CSV=${snapshots_csv},BASE_PATH=${BASE_PATH},SIMULATION_NAME=${SIMULATION_NAME},CONDA_ENV=${CONDA_ENV},PARTICLE=${PARTICLE},BACKEND=${BACKEND},GRID=${GRID},NCPUS=${NCPUS},THREADS=${THREADS},RESOURCE_SIZE=evolution,MEMORY_LIMIT=${MEM},MEMORY_SAFETY_FRACTION=${MEMORY_SAFETY_FRACTION},RADIUS_BINS=${RADIUS_BINS},RADIUS_BIN_BATCH_SIZE=${RADIUS_BIN_BATCH_SIZE},RADIUS_MODE=${RADIUS_MODE},MAS=${MAS},LOAD_MODE=${LOAD_MODE},CHUNK_SIZE=${CHUNK_SIZE},MAX_FULL_LOAD_GB=${MAX_FULL_LOAD_GB},SUMMARY_CACHE=${SUMMARY_CACHE},SUMMARY_CACHE_DIR=${SUMMARY_CACHE_DIR},WORK_PARTITION=${WORK_PARTITION},MAX_FILE_READERS=${MAX_FILE_READERS},CLUMPING_MAX_GRID_CELLS=${CLUMPING_MAX_GRID_CELLS},PROGRESS_INTERVAL=${PROGRESS_INTERVAL},VERBOSE=${VERBOSE},TARGET_PARTICLE_TYPE=${TARGET_PARTICLE_TYPE},TARGET_BACKEND=${TARGET_BACKEND},MASK_PARTICLE_TYPE=${MASK_PARTICLE_TYPE},MASK_BACKEND=${MASK_BACKEND},TARGET_RADIUS_MODE=${TARGET_RADIUS_MODE},MASK_RADIUS_MODE=${MASK_RADIUS_MODE},SIGMA_BAR_ION_CM2=${SIGMA_BAR_ION_CM2},SIGMA_BAR_ION_SOURCE=${SIGMA_BAR_ION_SOURCE}" \
  scripts/clumping_evolution_job.pbs
